# Generated by Django 2.2.12 on 2021-03-01 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('legal_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('caregiver', models.BooleanField()),
                ('patient', models.BooleanField()),
                ('adress', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('employer', models.CharField(max_length=30)),
                ('work_title', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('job_description', models.CharField(max_length=150)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Locations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.User')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('start_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('study', models.CharField(max_length=30)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Locations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.User')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('tart_date', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('the_type', models.CharField(max_length=30)),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_age', models.IntegerField()),
                ('salary_start', models.IntegerField()),
                ('salary_end', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Locations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.User')),
            ],
        ),
        migrations.CreateModel(
            name='Job_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Jobs')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Services')),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Skills')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.User')),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Services')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.User')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField()),
                ('afternoon', models.BooleanField()),
                ('night', models.BooleanField()),
                ('days', models.CharField(max_length=60)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('caregiver_offer', models.IntegerField()),
                ('patient_offer', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Jobs')),
            ],
        ),
    ]
