# Generated by Django 2.2.12 on 2021-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='patient_phone',
            field=models.CharField(max_length=10),
        ),
    ]
