# Generated by Django 2.2.12 on 2021-03-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20210302_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location_id',
            field=models.CharField(max_length=30),
        ),
    ]
